#ifndef __TRANSPORT_CONFIG_H
#define __TRANSPORT_CONFIG_H

/* Load and unload thresholds */
#define TRANSPORT_LOAD_THRESHOLD_G             200.0f
#define TRANSPORT_UNLOAD_EMPTY_G               50.0f
#define TRANSPORT_WAIT_LOAD_THRESHOLD_G        200.0f
#define TRANSPORT_WAIT_LOAD_SAMPLE_MS          500U
#define TRANSPORT_WAIT_LOAD_HOLD_MS            2000U
#define TRANSPORT_WAIT_LOAD_READY_TIMEOUT_MS   12000U
#define TRANSPORT_WAIT_LOAD_READY_MIN_G        180.0f
#define TRANSPORT_WAIT_LOAD_DISTURB_DIFF_G     30.0f
#define TRANSPORT_WAIT_LOAD_DISTURB_COUNT      2U
#define TRANSPORT_WAIT_LOAD_WINDOW_SIZE        5U

/* Obstacle and outbound tracking */
#define TRANSPORT_OBSTACLE_STOP_CM             30U
#define TRANSPORT_OBSTACLE_RESUME_CM           35U
#define TRANSPORT_MOTION_COMMAND_TIMEOUT_MS    250U
#define TRANSPORT_LINE_LOST_SEARCH_TIMEOUT_MS  5000U
#define TRANSPORT_END_MARK_RAW                 0x0FU
#define TRANSPORT_END_MARK_CONFIRM_MS          2500U
#define TRANSPORT_END_MARK_CONFIRM_SPEED       80
#define TRANSPORT_MIN_RUN_BEFORE_END_MS        1200U
#define TRANSPORT_MIN_PULSE_BEFORE_END         0L
#define TRANSPORT_LOAD_CHECK_TIMEOUT_MS        3000U
#define TRANSPORT_ARRIVED_PROMPT_MS            320U
#define TRANSPORT_OBSTACLE_TIMEOUT_MS          8000U

/* Unload and servo flow */
#define TRANSPORT_UNLOAD_WAIT_MS               2500U
#define TRANSPORT_SERVO_CLOSE_WAIT_MS          500U
#define TRANSPORT_FINISH_HOLD_MS               3000U
#define TRANSPORT_MAX_UNLOAD_RETRY             5U
#define TRANSPORT_TURN_BEFORE_UNLOAD_TIMEOUT_MS 1200U
#define TRANSPORT_TURN_BEFORE_UNLOAD_STALL_CHECK_MS 300U
#define TRANSPORT_TURN_BEFORE_UNLOAD_MIN_PULSE 20L
#define TRANSPORT_TURN_BEFORE_UNLOAD_SPEED     110
#define TRANSPORT_TURN_BEFORE_UNLOAD_PULSE     300L

/* Return search and return tracking */
#define TRANSPORT_RETURN_TURN_SPEED            180
#define TRANSPORT_RETURN_TURN_TIMEOUT_MS       7000U
#define TRANSPORT_RETURN_TURN_180_PULSE        3600L
#define TRANSPORT_HOME_TURN_SPEED              180
#define TRANSPORT_HOME_TURN_TIMEOUT_MS         7000U
#define TRANSPORT_HOME_TURN_180_PULSE          3600L
#define TRANSPORT_RETURN_SEARCH_SPEED          120
#define TRANSPORT_RETURN_SEARCH_STEP_MS        160U
#define TRANSPORT_RETURN_SEARCH_PAUSE_MS       80U
#define TRANSPORT_RETURN_SEARCH_MIN_SCAN_MS    700U
#define TRANSPORT_RETURN_SEARCH_CENTER_CONFIRM_MS 180U
#define TRANSPORT_RETURN_SEARCH_TIMEOUT_MS     10000U
#define TRANSPORT_RETURN_SEARCH_MAX_SPAN_STEPS 6U
#define TRANSPORT_RETURN_LINE_LOST_TIMEOUT_MS  1500U
#define TRANSPORT_RETURN_START_CONFIRM_SPEED   80
#define TRANSPORT_RETURN_MIN_MS                1200U
#define TRANSPORT_RETURN_TIMEOUT_MS            30000U
#define TRANSPORT_RETURN_START_MIN_PULSE       1500L
#define TRANSPORT_RETURN_START_RATIO_PERCENT   90U
#define TRANSPORT_START_MARK_CONFIRM_MS        2500U
#define TRANSPORT_RUN_TIMEOUT_MS               180000U

#endif /* __TRANSPORT_CONFIG_H */
